Upgrade @quasar/app-vite version to 1.9.5 version
To fix error message related with upgrade quasar to v2.16.9:

```
node:internal/modules/cjs/loader:1262
  const err = new Error(`Cannot find module '${request}'`);
              ^

Error: Cannot find module '/home/runner/work/ride-to-work-by-bike-frontend/ride-to-work-by-bike-frontend/node_modules/quasar/dist/transforms/import-transformation.js'
    at createEsmNotFoundErr (node:internal/modules/cjs/loader:1262:15)
    at finalizeEsmResolution (node:internal/modules/cjs/loader:1250:15)
    at resolveExports (node:internal/modules/cjs/loader:634:14)
    at Module._findPath (node:internal/modules/cjs/loader:724:31)
    at Module._resolveFilename (node:internal/modules/cjs/loader:1211:27)
    at Module._load (node:internal/modules/cjs/loader:1051:27)
    at Module.require (node:internal/modules/cjs/loader:1311:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (/home/runner/work/ride-to-work-by-bike-frontend/ride-to-work-by-bike-frontend/node_modules/@quasar/vite-plugin/dist/index.cjs:9:28)
    at Module._compile (node:internal/modules/cjs/loader:1469:14) {
  code: 'MODULE_NOT_FOUND',
  path: '/home/runner/work/ride-to-work-by-bike-frontend/ride-to-work-by-bike-frontend/node_modules/quasar/package.json'
}

Node.js v20.17.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
/home/runner/work/_actions/cypress-io/github-action/v6/dist/index.js:3900
                error = new Error(`The process '${this.toolPath}' failed with exit code ${this.processExitCode}`);
                        ^

Error: The process '/usr/local/bin/yarn' failed with exit code 1
    at ExecState._setResult (/home/runner/work/_actions/cypress-io/github-action/v6/dist/index.js:3900:25)
    at ExecState.CheckComplete (/home/runner/work/_actions/cypress-io/github-action/v6/dist/index.js:3883:18)
    at ChildProcess.<anonymous> (/home/runner/work/_actions/cypress-io/github-action/v6/dist/index.js:3777:27)
    at ChildProcess.emit (node:events:519:28)
    at maybeClose (node:internal/child_process:1105:16)
    at ChildProcess._handle.onexit (node:internal/child_process:305:5)
```