src/components/routes: add component RoutesMap for entring routes via a map interface (#470)
* integrate openlayers library

* routes map docs

* routes map with controls and undo

* map line vertexes (start, middle, finish)

* enable point deletion

* refactor and cleanup

* cleanup and refactor

* add ability to save routes

* add route length measure function

* use EPSG:3857 projection

* refactor saving routes

* types and docs

* format route length

* fix map control layer stacking

* toolbar buttons interaction

* docs update

* add centering on selected route

* add useGeographic and center on my location

* fix length after introducing useGeographic

* refactor toolbar component

* add core tests for toolbar

* options inject

* routes map toolbar wrapper div

* route map + list sizing

* core testing

* add tooltip on draw

* remove unused styles

* map settings as global variables

* docs update

* replace console log with quasar notify

* replace inline svgs with import

* useRoutesMapTooltip function docs

* routesmaptoolbar refactor test selectors and variabels

* fix @return docs parameter typo

* routes map zoom control default labels

* geocoding API URL global var

* fix typescript issue

* default route start and finish

* use route direction icon

* grey variable

* add map source from rtwbb

* add tooltips

* fix types

* clear undo history after save

* tooltip delay in a var

* unify naming

* routeListSelected fixture

* test route logging

* extend draw test

* add html comments

* expand tooltip info

* tooltip content docs

* logged routes storage

* edit single route

* docs and cleanup

* disabled state for toolbar buttons

* update tests

* map routes empty state

* route-list mobile height

* fix list height desktop

* add transport type tooltip label

* map toolbar dynamic tooltips

* add toggle between source types

* set default map source

* add select menu source

* test source select

* fix undo actions for route edits by adding a history entry on load

* clear edited routes after draw toggle

* fix types and docs

* update fixtures for tests and live

* update and test map toolbar

* routes map toolbar control

* update defaultInteractions to fix tests

* routes map comments

* fix history issue and extend tests

* update image snapshot

* fix eslint error + duplicate tranlation keys

* Regenerate yarn.lock

* Fix missing vue3-openlayers lib peer dependencies

Libs: ol, ol-ext, ol-contextmenu

Fix rebase error.

* test/cypress/support: fix import material-symbols-sharp icon set

Error related with upgrade Quasar framework lib to 2.17.2 version

Fix run Cypress component tests.

Cypress component tests error:

```
 1) An uncaught error was detected outside of a test

  0 passing (92ms)
  1 failing

  1) An uncaught error was detected outside of a test:
     TypeError: The following error originated from your test code, not from Cypress.

  > window.Quasar is undefined

When Cypress detects uncaught errors originating from your test code it will automatically fail the current test.

Cypress could not associate this error to any specific test.

We dynamically generated a new test to display this failure.
  at node_modules/quasar/dist/icon-set/material-symbols-sharp.umd.prod.js (http://localhost:9000/__cypress/src/node_modules/.q-cache/vite/spa/deps/quasar_dist_icon-set_material-symbols-sharp_umd_prod.js?v=9d544864:11:7)
  at node_modules/quasar/dist/icon-set/material-symbols-sharp.umd.prod.js (http://localhost:9000/__cypress/src/node_modules/.q-cache/vite/spa/deps/quasar_dist_icon-set_material-symbols-sharp_umd_prod.js?v=9d544864:12:7)
  at __init (http://localhost:9000/__cypress/src/node_modules/.q-cache/vite/spa/deps/chunk-J43GMYXM.js?v=c246f036:8:56)
  at <unknown> (http://localhost:9000/__cypress/src/node_modules/.q-cache/vite/spa/deps/quasar_dist_icon-set_material-symbols-sharp_umd_prod.js?v=9d544864:17:69)
```

* Disable run Cypress RoutesMap component tests file

File tests require review/refactor/extends tests.

---------

Co-authored-by: Šimon Macek <simon.macek@proficio.cz>
Co-authored-by: Tomas Zigo <tomas.zigo@slovanet.sk>