Revert "Update dependency cypress-terminal-report to v7.3.0 (#1114)"
This reverts commit 273153e0450dee7019937f5c416eb4e50710e482.

Some Cypress component test fails (runned from the web browser GUI) with
error message:

```
TypeError: Cannot read properties of null (reading 'length')
```